linters:
  enable:
    - gocritic
    - goimports
    - exhaustive
    - makezero
    - maligned
    - misspell
    - nolintlint
    - prealloc
    - predeclared
    - scopelint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - scopelint

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
