language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh
    | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - make qa

after_success:
  - curl -sfL https://codecov.io/bash | bash
